### ISSUE TITLE
With Arabic set as browser/system language, ExtendedQueryParameters.ToTridionQuery() fail

### ISSUE THREAD

**Issue by patrykgliwinski** [dd4t/DD4T.Providers.SDLTridion2011sp1#5]
With Arabic set as browser/system language, ExtendedQueryParameters.ToTridionQuery() method fails with the following trace:

2015-09-23 15:12:05,179 [118] ERROR Core.Helpers.HtmlHelperExtensions - HtmlHelperExtensions
System.Web.HttpException (0x80004005): Error executing child request for handler 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper'. ---> System.ArgumentOutOfRangeException: Specified time is not supported in this calendar. It should be between 04/30/1900 00:00:00 (Gregorian date) and 11/16/2077 23:59:59 (Gregorian date), inclusive.
Parameter name: time
at System.Globalization.UmAlQuraCalendar.CheckTicksRange(Int64 ticks)
at System.Globalization.UmAlQuraCalendar.GetDatePart(DateTime time, Int32 part)
at System.DateTimeFormat.FormatCustomized(DateTime dateTime, String format, DateTimeFormatInfo dtfi, TimeSpan offset)
at System.DateTimeFormat.Format(DateTime dateTime, String format, DateTimeFormatInfo dtfi, TimeSpan offset)
at DD4T.Providers.SDLTridion2011sp1.ExtendedQueryParameters.ToTridionQuery()
at DD4T.Providers.SDLTridion2011sp1.TridionComponentProvider.FindComponents(IQuery query)
...

Original issue:
https://github.com/dd4t/dynamic-delivery-4-tridion/issues/26
Pull Request:
https://github.com/dd4t/dynamic-delivery-4-tridion/pull/27

**Comment by quirijnslings** [comment]
It looks like the UmAlQuraCalendar is set as your standard calendar. I'm just guessing, but if you would use that same calendar when you set the DateTime value of the MetaQueryItem when you create the ExtendedQueryParameters, wouldn't that solve the problem?

**Comment by quirijnslings** [comment]
@patrykgliwinski Have you tried my suggestion?

**Comment by patrykgliwinski** [comment]
In our project we use the default value of DateTime.MinValue which then
fails for arabic browsers when translated to their calendar, so in the end
we're just forcing culture through through system.web.globalisation entry
which worked as a workaround for us.

**Comment by quirijnslings** [comment]
I will close it then, as I don't see an easy fix and there is a work-around.
